{"error": {
  "code": 400,
  "context": "Test file ExTest1.json for course 11121112333",
  "details": [
    {
      "code": "Exception",
      "message": "caught and rethrow from level: 1112333"
    },
    {
      "code": "Exception",
      "message": "caught and rethrow from level: 333"
    },
    {
      "code": "Exception",
      "message": "top level exception thrown by exception test when course string ran out"
    }
  ],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 86",
    "    TestExceptions.java: sampleMethod3: 81",
    "    TestExceptions.java: callHigher: 96",
    "    TestExceptions.java: sampleMethod3: 81",
    "    TestExceptions.java: callHigher: 96",
    "    TestExceptions.java: sampleMethod3: 81",
    "    TestExceptions.java: callHigher: 96",
    "    TestExceptions.java: sampleMethod2: 73",
    "    (continued below)",
    "caught and rethrow from level: 333",
    "    TestExceptions.java: sampleMethod2: 76",
    "    TestExceptions.java: callHigher: 93",
    "    TestExceptions.java: sampleMethod1: 68",
    "    TestExceptions.java: callHigher: 90",
    "    TestExceptions.java: sampleMethod1: 68",
    "    TestExceptions.java: callHigher: 90",
    "    TestExceptions.java: sampleMethod1: 68",
    "    TestExceptions.java: callHigher: 90",
    "    TestExceptions.java: sampleMethod2: 73",
    "    (continued below)",
    "caught and rethrow from level: 1112333",
    "    TestExceptions.java: sampleMethod2: 76",
    "    TestExceptions.java: callHigher: 93",
    "    TestExceptions.java: sampleMethod1: 68",
    "    TestExceptions.java: callHigher: 90",
    "    TestExceptions.java: sampleMethod1: 68",
    "    TestExceptions.java: callHigher: 90",
    "    TestExceptions.java: sampleMethod1: 68",
    "    TestExceptions.java: callHigher: 90",
    "    TestExceptions.java: runCourse: 112",
    "    TestExceptions.java: runTests: 36",
    "    TestRecorderText.java: parseArgsRunTests: 632",
    "    TestExceptions.java: main: 139"
  ]
}}